name: narps_open_pipelines
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - pip
  - traits 
  - jupyter 
  - nilearn 
  - graphviz 
  - nipype 
  - scikit-image
  - pip:
    - matplotlib
